urls.py
# -*- coding: utf-8 -*-
from django.conf.urls.defaults import patterns, include, url
from solutioner.views import *
from solutioner.users.views import *
from solutioner.solutions.views import *
from solutioner.tags.views import *
from solutioner.categories.views import *
#from solutioner.comments.views import *
import os
from django.conf import settings
from django.shortcuts import render_to_response
from django.conf.urls.defaults import *
from django.contrib import admin
admin.autodiscover()
from solutioner.sitemap.models import *
from solutioner.support.views import *
from solutioner.comments.views import *
from solutioner.events.views import *
from solutioner.widgets.views import *
from django.utils import simplejson
from solutioner.search.views import *


def alexa_confirm(request):
  return render_to_response('o0vyQVHfO3qLHSIFLr79SDqNZIo.html')
  
def robots_txt(request):
  return render_to_response('robots.txt', mimetype="text/plain")

sitemaps = {
    'solutions': SolutionSitemap,
}
urlpatterns = patterns('django.contrib.sitemaps.views',
    (r'^sitemap\.xml$', 'index', {'sitemaps': sitemaps}),
    (r'^sitemap-(?P<section>.+)\.xml$', 'sitemap', {'sitemaps': sitemaps}),
)


from sorl.thumbnail import get_thumbnail
from django.http import HttpResponse
def thumbnailer(request,wsize, hsize, url):
  size = unicode(wsize)+'x'+unicode(hsize)
  im = get_thumbnail(url, size, crop='center', quality=100)
  return HttpResponse(im.read(), mimetype="image/jpeg")




from solutioner.tags.models import Tag

def jauto(request):
  q = unicode(request.GET['search'])
  tags_found1 = Tag.objects.filter(name__istartswith=q).order_by('-used_no', 'name')[:4]
  tags_found2 = []
  tags_count = tags_found1.count()
  if tags_count < 4:
    r = 4 - tags_count
    tags_found2 = Tag.objects.filter(name__icontains=q).exclude(name__istartswith=q).order_by('-used_no', 'name')[:r]
  tags_found = list(tags_found1) + list(tags_found2)
  jjson = simplejson.dumps(map(unicode, tags_found))
  return HttpResponse(jjson, mimetype='application/json')



from django.conf.urls.defaults import *
from django.contrib.auth.views import password_reset
from solutioner.users.views import RegisterWizard
from solutioner.users.forms import RegisterForm, RegisterCaptchaForm

urlpatterns += patterns('',
  url(r'^admin/', include(admin.site.urls)),
  #url(r'^comments/', include('django.contrib.comments.urls')),
  url(r'^$', home),
  url(r'^login/$', login),
  url(r'^logout/$', logout),
  url(r'^register/$', RegisterWizard.as_view([RegisterForm, RegisterCaptchaForm] )),
  #url(r'^register/$', register_testver),
  #url(r'^addcomment/$', add_comment),
  url(r'^solutions/add/$', add_solution),
  url(r'^profile/([.\w\d]+)/info/$', profile_info),
  url(r'^profile/edit/$', edit_profile),
  url(r'^profile/edit/password/change/$', change_password),
  url(r'^profile/edit/privacy/settings/$', privacy_settings),
  url(r'^profile/edit/notifications/settings/$', notifications_settings),
  url(r'^profile/([.\w\d]+)/solutions/$', profile_solutions),
  url(r'^profile/([.\w\d]+)/$', profile_desk),
  url(r'^profile/([.\w\d]+)/desk/$', profile_desk),
  url(r'^profile/([.\w\d]+)/scores/$', profile_scores),
  url(r'^profile/([.\w\d]+)/votes/$', profile_votes),
  url(r'^profile/([.\w\d]+)/follow/$', profile_follow),
  url(r'^graphs/([.\w\d]+)/desk_comments/$', desk_comments),
  url(r'^graphs/comments/(\d+)/$', get_comment_by_id),
  url(r'^graphs/comments/(\d+)/([.\w\d]+)/$', get_comment_by_id),
  url(r'^solutions/view/(\d+)/$', view_solution),
  url(r'^solutions/edit/(\d+)/$', edit_solution), 
  url(r'^ajax/solutions/vote/(\d+)/$', ajax_sol_vote),
  url(r'^graphs/solution/(\d+)/$', graphs_solution),
  url(r'^graphs/user/([.\w\d]+)/$', graphs_user),
  url(r'^solutions/view/$', solutionList),
  #url(r'^search/$', include('haystack.urls')),
  url(r'^search/$', search_page),
  url(r'^tags/(.+)/$', tags_view),
  url(r'^tags/$', tags),
  url(r'^categories/$', categories),
  url(r'^categories/(.+)/$', categories_view),
  url(r'^o0vyQVHfO3qLHSIFLr79SDqNZIo.html/$', alexa_confirm),
  url(r'^robots.txt/$', robots_txt),
  url(r'^graphs/([.\w\d]+)/solutions/$', graphs_user_solutions),
  url(r'^rm_solution/$', rm_solution),
  url(r'^rm_comment/$', rm_comment),
  url(r'^thumbs/(\d+)x(\d+)/(.+)$', thumbnailer),
  url(r'^follow/$', user_follow),
  url(r'^ajax/follow/$', user_follow),
  url(r'^ajax/jauto/$', jauto),
  url(r'^profile/edit/password/reset/$', password_reset, {'post_reset_redirect': '/'}),
  url(r'^reset/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$', 'django.contrib.auth.views.password_reset_confirm', {'post_reset_redirect': '/logout/' }),
  url(r'^developers/$', developers),
  url(r'^licenses/$', licenses),
  url(r'^termsofservice/$', terms_of_service),
  url(r'^privacypolicy/$', privacy_policy),
  url(r'^aboutus/$', about_us),
  url(r'^contactus/$', support_contactus),
  url(r'^ajax/notifications/$', notifications),
  url(r'^ajax/last_checked/$', last_checked),
  url(r'^notifications/$', notifications_page),
  url(r'^graphs/home_events/$', get_home_events),
  url(r'^graphs/([.\w\d]+)/profile_events/$', get_profile_events),
  url(r'^solutions/fork/$', fork_solution),
  url(r'^ajax/follow_suggest/$', follow_suggest),
  url(r'^ajax/friend_finder/$', friend_finder),
  url(r'^ajax/solutions/(\d+)/view/comments/$', solution_comments),

  

  

)

categories/models.py
from django.db import models

class Category(models.Model):
  name = models.CharField(max_length=10000)
  related_to = models.CharField(blank=True, max_length=10000)
  
  def __unicode__(self):
    return self.name

search/models.py
from django.db import models

# Create your models here.

tags/models.py
from django.db import models

class Tag(models.Model):
  name = models.CharField(blank=False, max_length=50)
  used_no = models.BigIntegerField(blank=True, null=True, default=0)
  is_suspended = models.BooleanField(default=False)
  is_deleted = models.BooleanField(default=False)
  
  def __unicode__(self):
    return '%s'%(self.name)

users/models.py
from django.db import models
from django.contrib.auth.models import User as authUser
from sorl.thumbnail import ImageField
import uuid
from solutioner.users.country_field import COUNTRIES2 as COUNTRY_CHOICES
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes import generic


class OwnershipManager(models.Manager):
  def create_ownership(self, owner_inst, object_inst):
    owner_ct = ContentType.objects.get_for_model(owner_inst)
    owner_id = owner_inst.id
    object_ct = ContentType.objects.get_for_model(object_inst)
    object_id = object_inst.id
    
    return Ownership.objects.create(owner_ct=owner_ct, owner_id=owner_id, object_ct=object_ct, object_id=object_id)

  def get_or_create_ownership(self, owner_inst, object_inst):
    try:
      return Ownership.objects.get(object_ct = ContentType.objects.get_for_model(object_inst), object_id = object_inst.id), False
    except:
      owner_ct = ContentType.objects.get_for_model(owner_inst)
      owner_id = owner_inst.id
      object_ct = ContentType.objects.get_for_model(object_inst)
      object_id = object_inst.id
      return Ownership.objects.create(owner_ct=owner_ct, owner_id=owner_id, object_ct=object_ct, object_id=object_id), True
    
  
  def get_ownership(self, object_inst):
    try:
      return Ownership.objects.get(object_ct = ContentType.objects.get_for_model(object_inst), object_id = object_inst.id)
    except:
      return None
      
  def get_ownership_ct_id(self, object_inst):
    try:
      owner = Ownership.objects.get(object_ct = ContentType.objects.get_for_model(object_inst), object_id = object_inst.id)
      return owner.owner_ct, owner.owner_id
    except:
      return None
    
class Ownership(models.Model):
  owner_ct = models.ForeignKey(ContentType, related_name='ownership_owner')
  owner_id = models.PositiveIntegerField()
  object_ct = models.ForeignKey(ContentType, related_name='ownership_object')
  object_id = models.PositiveIntegerField()
  is_suspended = models.BooleanField(default=False)
  is_deleted = models.BooleanField(default=False)

  owner = generic.GenericForeignKey('owner_ct', 'owner_id')
  object = generic.GenericForeignKey('object_ct', 'object_id')

  objects = OwnershipManager()
  
  class Meta:
    unique_together = ('object_ct', 'object_id')
   
  def __unicode__(self):
    return '%s | %s | %s' % (self.owner, self.object)


class License(models.Model):
  license = models.CharField(max_length=100)
  license_url = models.CharField(max_length=10000)

  def __unicode__(self):
    return '%s'%(self.license)

class Source(models.Model):
  source = models.CharField(max_length=100)
  url = models.CharField(max_length=200)
  image = models.CharField(max_length=200)
  description = models.CharField(max_length=1000)
  like = models.ManyToManyField(authUser, blank=True, null=True, default=None, related_name='sourceslike_users')
  licenses = models.ManyToManyField(License, blank=True, null=True, default=None, related_name='licenses_users')
  viewed = models.BigIntegerField(blank=True, null=True, default=0)
  is_deleted = models.BooleanField(default=False)
  
  def __unicode__(self):
    return '%s'%(self.source)

def content_file_name(instance, filename):
  ext = filename.split('.')[-1]
  filename = "%s.%s" % (uuid.uuid4(), ext)
  return '/'.join(['profiles/pictures', filename])

GENDER_CHOICES = (
  ('N', '-'),
  ('M', 'Male'),
  ('F', 'Female'),
)


class User(models.Model):
  user = models.ForeignKey(authUser)
  gender = models.CharField(max_length=1, choices=GENDER_CHOICES, default='N')
  image = models.ImageField(upload_to=content_file_name)
  location = models.CharField(max_length=3, choices=COUNTRY_CHOICES, default='N')
  birthdate = models.DateField(blank=True, null=True)
  website = models.CharField(blank=True, null=True, max_length=1000)
  following = models.ManyToManyField(authUser, blank=True, null=True, default=None, related_name='users_usersfollowing')
  last_checked_id = models.BigIntegerField(default=0)
  is_suspended = models.BooleanField(default=False)
  is_deleted = models.BooleanField(default=False)
  
  def __unicode__(self):
    return '%s'%(self.user)
    
class NotificationSettings(models.Model):
  user = models.ForeignKey(authUser)
  comment_on_desk = models.BooleanField(default=True)
  comment_on_solution = models.BooleanField(default=True)
  is_deleted = models.BooleanField(default=False)
  
  def __unicode__(self):
    return '%s'%(self.user)

 
class ExternalUser(models.Model):
  source = models.ForeignKey(Source)
  username = models.CharField(max_length=100)
  image = models.CharField(blank=True, max_length=1000)
  url = models.CharField(blank=True, max_length=1000)
  is_suspended = models.BooleanField(default=False)
  is_deleted = models.BooleanField(default=False)
  
  def __unicode__(self):
    return '%s'%(self.username)
    

solutions/forms.py
from django import forms
from django.contrib.auth.models import User
from django.shortcuts import render_to_response
from solutioner.categories.models import Category
from lxml.html import fromstring
from lxml import etree
from lxml.html.clean import Cleaner
import lxml
from lxml.html import clean

def clean_html(html):
  html = lxml.html.fromstring(html)
  #clean.defs.safe_attrs=frozenset(['href','src'])
  cleaner = clean.Cleaner(allow_tags=['h1','h2','h3','h4','h5','h6','p','div','span','pre','code','img','a','br'], safe_attrs_only=True, 
remove_unknown_tags=False)
  cleaned = cleaner.clean_html(html)
  return lxml.html.tostring(cleaned)


class AddSolution(forms.Form):
  def __init__(self, *args, **kwargs):
    super(AddSolution, self).__init__(*args, **kwargs)
    self.fields['problem_desc'].label = "Problem Description (optional)"

  problem = forms.CharField(max_length=200, error_messages={'required': '*'})
  problem.widget.attrs = {'class': 'problem_input'}
  problem_desc = forms.CharField(widget=forms.Textarea, required=False)
  problem_desc.widget.attrs = {'class': 'problem_desc_textarea'}
  category =  forms.ModelChoiceField(queryset=Category.objects.all(),initial='1', error_messages={'required': '*'})
  #category.widget.attrs = {'class': 'uiselectmenu'}
  solution = forms.CharField(widget=forms.Textarea, error_messages={'required': '*'})
  solution.widget.attrs = {'class': 'solution_textarea'}
  tags = forms.CharField(required=False, max_length = 10000, widget=forms.HiddenInput)
  
  def clean_title (self):
    title = self.cleaned_data['title']
    if len(title) > 200:
      raise forms.ValidationError("Title can't have more than 10000 characters")
    return title
 
  def clean_problem_desc (self):
    problem_desc = self.cleaned_data['problem_desc']
    if problem_desc == '<br>':
      problem_desc = ''
    if problem_desc:
      try:
        return clean_html(problem_desc)
      except:
        raise forms.ValidationError("*")
    else:
      return problem_desc
  
  def clean_solution (self):
    solution = self.cleaned_data['solution']
    if solution == '<br>':
      solution = ''
      raise forms.ValidationError("*")
    if solution:
      return clean_html(solution)
    else:
      return solution

categories/views.py
from django.shortcuts import render_to_response
from django.template import RequestContext
from solutioner.categories.models import Category
from solutioner.solutions.models import Solution
from solutioner.solutions.views import per_page_creator

def categories_view(request, category):
  output_dict = per_page_creator(request, Solution.objects.filter(category=Category.objects.get(name=category)), table_type='solution')
  output_dict_add = {'category': category}
  output_dict.update(output_dict_add)
  return render_to_response("categories_view.html", output_dict, context_instance=RequestContext(request))
  
def categories(request):
  output_dict = per_page_creator(request, Category.objects, order='name')
  return render_to_response("categories.html", output_dict, context_instance=RequestContext(request))

search/views.py
from django.http import HttpResponse
from django.shortcuts import render_to_response
from django.utils import simplejson
from django.contrib.auth.models import User
from django.db.models import Q
from django.template import RequestContext


def friend_finder(request):
  q = unicode(request.GET['search'])
  tags_found1 = User.objects.filter(Q(first_name__istartswith=q) | Q(last_name__istartswith=q)).values('username','first_name','last_name').order_by('?')[:4]
  tags_found2 = []
  tags_count = tags_found1.count()
  if tags_count < 4:
    r = 4 - tags_count
    tags_found2 = User.objects.filter(Q(first_name__icontains=q) | Q(last_name__icontains=q)).exclude(Q(first_name__istartswith=q) | Q(last_name__istartswith=q)).values('username','first_name','last_name').order_by('?')[:r]
  tags_found = list(tags_found1) + list(tags_found2)
  jjson = simplejson.dumps(tags_found)
  return HttpResponse(jjson, mimetype='application/json')

def search_page(request):
  try:
    search_target = request.GET['search_target']
    if search_target != 'users' and search_target != 'solutions':
      search_target = 'users'
  except:
    search_target = 'users'
  return render_to_response('search.html', {'search_target': search_target}, context_instance=RequestContext(request))

tags/views.py
from django.shortcuts import render_to_response
from django.template import RequestContext
from solutioner.tags.models import Tag
from solutioner.solutions.views import per_page_creator

def tags_view(request, tag):
  output_dict = per_page_creator(request, Tag.objects.get(name=tag).solution_tags.filter(is_deleted=False), 'solution')
  output_dict_add = {'tag': tag}
  output_dict.update(output_dict_add)
  return render_to_response("tags_view.html", output_dict, context_instance=RequestContext(request))


def tags(request):
  output_dict = per_page_creator(request, Tag.objects, order='-used_no', default_per_no=25)
  return render_to_response("tags.html", output_dict, context_instance=RequestContext(request))

templates/2col.html
{% extends "base.html" %}


{% block content %}

<div class="topdiv" style="margin-bottom: 20px;">
{% block topdiv %}
{% endblock %}
</div>

<div class="leftcolumn">
{% block leftcol %}
{% endblock %}
</div>

<div class="midcolumn">
{% block midcol %}
{% endblock %}
</div>

<div class="rightcolumn">
{% block rightcol %}

{% block beforeads %}
{% endblock %}

<div style="padding: 5px; margin-top:5px;">
<center>
<script type="text/javascript"><!--
google_ad_client = "ca-pub-8637683020168924";
/* Side Bar - Long */
google_ad_slot = "6387300074";
google_ad_width = 160;
google_ad_height = 600;
//-->
</script>
<!--<script type="text/javascript"
src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>-->
</center>
</div>
{% block afterads %}
{% endblock %}

{% endblock %}
</div>



{% endblock %}

templates/REMOVEME_solution_ajax.html
{% block solution_item %}
{% load truncatechars %}
<hr />
<div style="padding: 10px">
<div style="float:right">Added: <span id="dateadded" class="rel" title="{{ solution.datetime_added }}">{{ solution.datetime_added|timesince }} ago</span></div>
<div style="font-size: 9px;">Category: <a href="/categories/{{solution.category|urlencode}}">{{ solution.category }}</a> | <b>Viewed:</b> {{ solution.viewed }}</div>
<div style="clear: both"></div>
<div style="background: #EAEAEA; padding: 10px 5px 10px 5px; margin-bottom: 2px;"><b>Problem:</b> <a href="/solutions/view/{{ solution.id }}/">{{ solution.problem|safe }}</a></div>
<div style="background: #EAEAEA; padding: 10px 5px 10px 5px; margin-bottom: 2px;"><b>Problem Description:</b> {{ solution.problem_desc|striptags|truncatechars:'300' }}</div>
<div style="background: #EAEAEA; padding: 10px 5px 10px 5px; margin-bottom: 2px;"><b>Solution:</b> {{ solution.solution|striptags|truncatechars:'300' }}</div>
{% if solution.tags %}<div class="tag_nob">Tags: {% for tag in solution.tags %}<a class="tag" href="/tags/{{tag|urlencode}}">{{ tag|safe }}</a> {% endfor %}</div>{% endif %}

<div style="float:right"><a id="view_solution" href="/solutions/view/{{ solution.id }}/">view solution</a></div>
{% if graphs_user_info.is_page_owner %}
<div style="float:right"><a id="edit_solution" href="/solutions/edit/{{ solution.id }}/">edit</a>|</div>
<div style="float:right">
<form action="/rm_solution/" method="post">{% csrf_token %}
  <input type="hidden" name="toRM" value="{{ solution.id }}" />
  <input type="submit" value="delete" id="delete_solution" class="delete_solution" />
</form>
</div>

{% endif %}
<span class="useful_solu">Useful votes got: {{ solution.useful_count }}</span> | <span class="unuseful_solu">Useful votes got: {{ solution.unuseful_count }}</span>
</div>
{% endblock %}

templates/categories_view.html
{% extends "2col.html" %}

{% block title %}{{ category }} Solutions{% endblock %}


{% block script %}
{% if not no_content %}
{% if 'Mathematics' in categories %}
<script type="text/x-mathjax-config">
  MathJax.Hub.Config({
    tex2jax: { inlineMath: [ ["$", "$"], ["\\\\(","\\\\)"] ], displayMath: [ ["$$","$$"], ["\\[", "\\]"] ], processEscapes: true, ignoreClass: "tex2jax_ignore|dno" }
  });
</script>    
<script type="text/javascript" src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=default"></script>   
{% endif %}
{% endif %}
    
{% endblock %} 

{% block topdiv %}

<li class="tag_nob">Category: <a class="tag" href="/categories/{{ category }}/">{{ category }}</a></li>

<div>Total Solutions available: {{ table_list_len }}</div>

{% if not no_content %}

{% if page_bar_mid|length != 1 %}
<p>
{% if previous_page %}
<span class="p02500"><a href="/categories/{{ category|urlencode }}/?page_no=1&per_page={{per_page_alloc}}">First</a></span>
<span class="p0505"><a href="/categories/{{ category|urlencode }}/?page_no={{previous_page}}&per_page={{per_page_alloc}}">Previous</a></span>
{% endif %}
<span class="page_no_container">
{% if page_bar_left %}
<span class="page_bar_left"><a href="/categories/{{ category|urlencode }}/?page_no={{page_bar_left}}&per_page={{per_page_alloc}}">{{page_bar_left}}</a> ...</span> 
{% endif %}

{% for page in page_bar_mid %}
{% if page == current_page %}
<a class="page_no current_page_no" href="/categories/{{ category|urlencode }}/?page_no={{page}}&per_page={{per_page_alloc}}">{{page}}</a>
{% else %}
<a class="page_no" href="/categories/{{ category|urlencode }}/?page_no={{page}}&per_page={{per_page_alloc}}">{{page}}</a>
{% endif %}
{% endfor %}

{% if page_bar_right %}
<span class="p05015"> ... <a href="/categories/{{ category|urlencode }}/?page_no={{page_bar_right}}&per_page={{per_page_alloc}}">{{page_bar_right}}</a></span>
{% endif %}
</span>
{% if next_page %}
<span class="p0505"><a href="/categories/{{ category|urlencode }}/?page_no={{next_page}}&per_page={{per_page_alloc}}">Next</a></span>
<span class="p00025"><a href="/categories/{{ category|urlencode }}/?page_no={{total_pages|length}}&per_page={{per_page_alloc}}">Last</a></span>
{% endif %}
</p>
{% endif %}
{% if total_pages|length > 1 or table_list_len >= default_per_no %}
<div>Items per page: 
<span class="page_no_container">
<a class="page_no {% if per_page_alloc == default_per_no %}current_page_no{% endif %}" href="/categories/{{ category|urlencode }}/?page_no=1&per_page={{default_per_no}}">{{default_per_no}}</a>
<a class="page_no {% if per_page_alloc == 40 %}current_page_no{% endif %}" href="/categories/{{ category|urlencode }}/?page_no=1&per_page=40">40</a>
<a class="page_no {% if per_page_alloc == 100 %}current_page_no{% endif %}" href="/categories/{{ category|urlencode }}/?page_no=1&per_page=100">100</a>
</span>
</div>
{% endif %}



{% endif %}
{% endblock %}


{% block leftcol %}

<div id="category_solution_list">
{% if no_content %}
This category has no items available
{% else %}

{% load truncatechars %}
{% for solution in table_list %}
{% include "solution_box.html" %}
{% endfor %}

{% if total_pages|length > 1 or table_list_len >= default_per_no %}
<div>Items per page: 
<span class="page_no_container">
<a class="page_no {% if per_page_alloc == default_per_no %}current_page_no{% endif %}" href="/categories/{{ category|urlencode }}/?page_no=1&per_page={{default_per_no}}">{{default_per_no}}</a>
<a class="page_no {% if per_page_alloc == 40 %}current_page_no{% endif %}" href="/categories/{{ category|urlencode }}/?page_no=1&per_page=40">40</a>
<a class="page_no {% if per_page_alloc == 100 %}current_page_no{% endif %}" href="/categories/{{ category|urlencode }}/?page_no=1&per_page=100">100</a>
</span>
</div>
{% endif %}

{% if page_bar_mid|length != 1 %}
<p>
{% if previous_page %}
<span class="p02500"><a href="/categories/{{ category|urlencode }}/?page_no=1&per_page={{per_page_alloc}}">First</a></span>
<span class="p0505"><a href="/categories/{{ category|urlencode }}/?page_no={{previous_page}}&per_page={{per_page_alloc}}">Previous</a></span>
{% endif %}
<span class="page_no_container">
{% if page_bar_left %}
<span class="page_bar_left"><a href="/categories/{{ category|urlencode }}/?page_no={{page_bar_left}}&per_page={{per_page_alloc}}">{{page_bar_left}}</a> ...</span> 
{% endif %}

{% for page in page_bar_mid %}
{% if page == current_page %}
<a class="page_no current_page_no" href="/categories/{{ category|urlencode }}/?page_no={{page}}&per_page={{per_page_alloc}}">{{page}}</a>
{% else %}
<a class="page_no" href="/categories/{{ category|urlencode }}/?page_no={{page}}&per_page={{per_page_alloc}}">{{page}}</a>
{% endif %}
{% endfor %}

{% if page_bar_right %}
<span class="p05015"> ... <a href="/categories/{{ category|urlencode }}/?page_no={{page_bar_right}}&per_page={{per_page_alloc}}">{{page_bar_right}}</a></span>
{% endif %}
</span>
{% if next_page %}
<span class="p0505"><a href="/categories/{{ category|urlencode }}/?page_no={{next_page}}&per_page={{per_page_alloc}}">Next</a></span>
<span class="p00025"><a href="/categories/{{ category|urlencode }}/?page_no={{total_pages|length}}&per_page={{per_page_alloc}}">Last</a></span>
{% endif %}
</p>
{% endif %}



{% endif %}

</div>
{% endblock %}

templates/notifications_settings.html
{% extends "settings.html" %}

{% block title %}Notifications Settings{% endblock %}


{% block form_content %}
<b>Notifications Settings</b>
{% if saved %}
<div><span style="color: green;">Changes have been saved</span></div>
{% endif %}
<hr>
<p>In following cases an email will be sent to your primary email address:</p>
<table>
  <tbody>
    <tr>
      <td><label for="idcomment_on_desk">When someone post on your desk</label></td>
      <td>{{ form.comment_on_desk }}</td>
      <td><div id="error">{% for error in form.comment_on_desk.errors %}{{ error }}{% endfor %}</div></td>
    </tr>
    <tr>
      <td><label for="id_comment_on_solution">When someone comment on your solution</label></td>
      <td>{{ form.comment_on_solution }}</td>
      <td><div id="error">{% for error in form.comment_on_solution.errors %}{{ error }}{% endfor %}</div></td>
    </tr>
  </tbody>
</table>
{% endblock %}

templates/o0vyQVHfO3qLHSIFLr79SDqNZIo.html
<html>
    <head>
        <meta name="alexaVerifyID" content="o0vyQVHfO3qLHSIFLr79SDqNZIo" />
    </head>
    <body>
        <p>Great! The file uploaded properly.  Now click the 'Verify my file' button to
        complete the process.</p>
    </body>
</html>